[TextBlock]
min_height = 100
placeholder = Escribe algo o pulsa '/' para comandos...

[HeaderBlock]
placeholder = Título de la nota

[PropertiesBlock]
panel_title = PROPIEDADES

[TableBlock]
min_columns = 1

